version: "3.9"

services:
  db:
    image: postgres:14.0-alpine
    hostname: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

    networks:
      - backend
    restart: always
  web:
    build: .
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
    command:
      - "python /usr/src/app/cloud_file_storage_controller/api/server.py"
    networks:
      - backend
    restart: always

networks:
  backend:
    driver: bridge