version: "3.9"

services:
  db:
    image: postgres:14.0-alpine
    hostname: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
#      - POSTGRES_DB="postgres"
#      - POSTGRES_USER="postgres"
#      - POSTGRES_PASSWORD="postgres"
    networks:
      - backend
  web:
    build: .
#    command: python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - .:/code
    ports:
      - "80:80"
#    environment:
#      - DATASOURCE_URL
#      - POSTGRES_NAME=postgres
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - backend


networks:
  backend:
    driver: bridge